add_newline = false
command_timeout = 1000

[character]
success_symbol = ">"
error_symbol = ">"

[directory]
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "git:"

[git_status]
disabled = false

[nodejs]
disabled = false

[package]
disabled = true
